name: photo_editor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  matrix_gesture_detector:
    git:
      url: https://github.com/aabidsayeed1/matrix_gesture_detector.git
  sticker_view: ^0.0.2
  shared_preferences: ^2.0.15
  stack_board: ^0.1.2
  dotted_border: ^2.0.0+3
  flutter_speed_dial: ^6.2.0
  get: ^4.6.5
  flutter_colorpicker: ^1.0.3
  google_fonts: ^3.0.1
      

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Light.ttf
    - family: PoiretOne
      fonts:
        - asset: fonts/PoiretOne-Regular.ttf
    - family: Monoton
      fonts:
        - asset: fonts/Monoton-Regular.ttf
    - family: BungeeInline
      fonts:
        - asset: fonts/BungeeInline-Regular.ttf
    - family: ConcertOne
      fonts:
        - asset: fonts/ConcertOne-Regular.ttf
    - family: FrederickatheGreat
      fonts:
        - asset: fonts/FrederickatheGreat-Regular.ttf
    - family: Martel
      fonts:
        - asset: fonts/Martel-ExtraLight.ttf
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
    - family: Vidaloka
      fonts:
        - asset: fonts/Vidaloka-Regular.ttf
    - family: Billabong
      fonts:
        - asset: fonts/Billabong.ttf
    - family: GrandHotel
      fonts:
        - asset: fonts/GrandHotel.otf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans.ttf
    - family: Oswald
      fonts:
        - asset: fonts/Oswald.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand.otf
    - family: BeautifulPeople
      fonts:
        - asset: fonts/BeautifulPeople.ttf
    - family: BeautyMountains
      fonts:
        - asset: fonts/BeautyMountains.ttf
    - family: BiteChocolate
      fonts:
        - asset: fonts/BiteChocolate.ttf
    - family: BlackberryJam
      fonts:
        - asset: fonts/BlackberryJam.ttf
    - family: Tomatoes
      fonts:
        - asset: fonts/Tomatoes.ttf
    - family: BunchBlossoms
      fonts:
        - asset: fonts/BunchBlossoms.ttf
    - family: CinderelaRegular
      fonts:
        - asset: fonts/CinderelaRegular.ttf
    - family: Countryside
      fonts:
        - asset: fonts/Countryside.ttf
    - family: Halimun
      fonts:
        - asset: fonts/Halimun.ttf
    - family: LemonJelly
      fonts:
        - asset: fonts/LemonJelly.ttf
    - family: QuiteMagicalRegular
      fonts:
        - asset: fonts/QuiteMagicalRegular.ttf
    - family: TropicalAsianDemoRegular
      fonts:
        - asset: fonts/TropicalAsianDemoRegular.ttf
    - family: VeganStyle
      fonts:
        - asset: fonts/VeganStyle.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
